### ISSUE TITLE
Exercise sheet

### ISSUE THREAD

**Issue by Timmifixedit** [aul12/PraktischeITSicherheit-Intel-SGX#4]

**Comment by aul12** [comment]
Aufbau:
 - [x] Einleitung: Was ist OpenSGX
 - [x] VM mit SGX heruterladen und starten
 - [x] `test.c` ausführen und schauen ob alles tut
 - [x] Erklärung E-Voting Anwendung
 - [x] Struktur E-Voting Anwendung
 - [x] Implementierung (mit kleiner Lib für Pipes)
 - [x] Intra Attestation
 - [x] Übungsblatt Intra Attestation
 - [x] Übungskonzept
 - [x] Fertige VM

**Comment by aul12** [comment]
Automatische Remote Attestation vor Wahl
